### PR TITLE
sir i want ur help , im making a app

### PR DESCRIPTION
**Pull request by lijubehera**

### CODE REVIEW

**Comment by lijubehera** [comment]
hii sir

**Comment by AkashNair-o** [comment]
> hii sir

**Comment by lijubehera** [comment]
Hi sir

**Comment by lijubehera** [comment]
Firebase connection nhi horhai .

**Comment by AkashNair-o** [comment]
Hello @lijubehera <https://github.com/lijubehera> ,
Please connect on my LinkedIn
<https://www.linkedin.com/in/akash-nair-92936418a>

**Comment by lijubehera** [comment]
Thanks, I will.

**Pull request closed without merging**
